FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y poppler poppler-cpp poppler-devel poppler-glib poppler-cpp-devel poppler-utils gcc-c++

RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/auth_provider
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/bedrock_provider
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/boto_client_provider
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/document_collections_handler
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/embeddings_provider
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/ingestion_status_provider
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/system_settings_provider
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/user_settings_provider
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/loaders
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/splitters
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/utils
COPY bedrock_provider/*requirements.txt /var/task/multi_tenant_full_stack_rag_application/bedrock_provider/
COPY embeddings_provider/*requirements.txt /var/task/multi_tenant_full_stack_rag_application/embeddings_provider/
COPY vector_store_provider/*requirements.txt /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/

RUN pip3 install -t /var/task -r multi_tenant_full_stack_rag_application/vector_store_provider/vector_ingestion_requirements.txt
RUN pip3 install -t /var/task -r multi_tenant_full_stack_rag_application/embeddings_provider/bedrock_embeddings_provider_requirements.txt
RUN pip3 install -t /var/task -r multi_tenant_full_stack_rag_application/bedrock_provider/bedrock_provider_requirements.txt
RUN pip3 install -t /var/task -r multi_tenant_full_stack_rag_application/vector_store_provider/opensearch_requirements.txt

COPY auth_provider/*.py /var/task/multi_tenant_full_stack_rag_application/auth_provider/
COPY boto_client_provider/*.py /var/task/multi_tenant_full_stack_rag_application/boto_client_provider/
COPY embeddings_provider/*.py /var/task/multi_tenant_full_stack_rag_application/embeddings_provider/
COPY ingestion_status_provider/*.py /var/task/multi_tenant_full_stack_rag_application/ingestion_status_provider/
COPY bedrock_provider/*.json /var/task/multi_tenant_full_stack_rag_application/bedrock_provider/
COPY bedrock_provider/*.py /var/task/multi_tenant_full_stack_rag_application/bedrock_provider/
COPY user_settings_provider/*.py /var/task/multi_tenant_full_stack_rag_application/user_settings_provider/
COPY vector_store_provider/*.py /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/
COPY vector_store_provider/loaders/*.py /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/loaders/
COPY vector_store_provider/loaders/*.txt /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/loaders/
COPY vector_store_provider/splitters/*.py /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/splitters/
COPY document_collections_handler/*.py /var/task/multi_tenant_full_stack_rag_application/document_collections_handler/
COPY system_settings_provider/*.py /var/task/multi_tenant_full_stack_rag_application/system_settings_provider/
COPY utils/*.py /var/task/multi_tenant_full_stack_rag_application/utils/
CMD [ "multi_tenant_full_stack_rag_application.vector_store_provider.vector_ingestion_handler.handler" ]

