FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y poppler poppler-cpp poppler-devel poppler-glib poppler-cpp-devel poppler-utils gcc-c++

RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/auth_provider
COPY auth_provider/*.py /var/task/multi_tenant_full_stack_rag_application/auth_provider/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/boto_client_provider
COPY boto_client_provider/*.py /var/task/multi_tenant_full_stack_rag_application/boto_client_provider/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/embeddings_provider
COPY embeddings_provider/*.py /var/task/multi_tenant_full_stack_rag_application/embeddings_provider/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/ingestion_status_provider
COPY ingestion_status_provider/*.py /var/task/multi_tenant_full_stack_rag_application/ingestion_status_provider/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/bedrock_provider
COPY bedrock_provider/*.json /var/task/multi_tenant_full_stack_rag_application/bedrock_provider/
COPY bedrock_provider/*.py /var/task/multi_tenant_full_stack_rag_application/bedrock_provider/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/user_settings_provider
COPY user_settings_provider/*.py /var/task/multi_tenant_full_stack_rag_application/user_settings_provider/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/loaders
COPY vector_store_provider/*.py /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/
COPY vector_store_provider/*requirements.txt /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/
COPY vector_store_provider/loaders/*.py /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/loaders/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/splitters
COPY vector_store_provider/splitters/*.py /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/splitters/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/document_collections_handler
COPY document_collections_handler/*.py /var/task/multi_tenant_full_stack_rag_application/document_collections_handler/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/system_settings_provider
COPY system_settings_provider/*.py /var/task/multi_tenant_full_stack_rag_application/system_settings_provider/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/utils
COPY utils/*.py /var/task/multi_tenant_full_stack_rag_application/utils/

RUN pip3 install -t /var/task -r /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/vector_ingestion_requirements.txt

ARG emb_provider_reqs
ENV EMB_PROVIDER_REQS=$emb_provider_reqs

RUN for req in $EMB_PROVIDER_REQS; do \
  pip3 install -r "multi_tenant_full_stack_rag_application/$req" -t /var/task; \
  done;

ARG vector_store_reqs
ENV VECTOR_STORE_REQS=$vector_store_reqs

RUN for req in $VECTOR_STORE_REQS; do \
  pip3 install -r "$req" -t /var/task; \
  done;


CMD [ "multi_tenant_full_stack_rag_application.vector_store_provider.vector_ingestion_handler.handler" ]

