FROM public.ecr.aws/lambda/python:3.13

RUN dnf install -y poppler poppler-cpp poppler-devel poppler-glib poppler-cpp-devel poppler-utils gcc-c++

RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/loaders
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/splitters
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/
RUN mkdir -p /var/task/multi_tenant_full_stack_rag_application/utils
# copy just the requirements, then do the pip installs, then copy all the source code. That way the 
# layers with the pip installs will be reused more often and avoid large uploads on re-deployment.
COPY ingestion_provider/vector_ingestion_requirements.txt /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/
COPY utils/utils_requirements.txt /var/task/multi_tenant_full_stack_rag_application/utils/
COPY ingestion_provider/loaders/docx_loader_requirements.txt multi_tenant_full_stack_rag_application/ingestion_provider/loaders/
COPY ingestion_provider/loaders/pdf_image_loader_requirements.txt multi_tenant_full_stack_rag_application/ingestion_provider/loaders
RUN pip3 install -t /var/task -r /var/task/multi_tenant_full_stack_rag_application/utils/utils_requirements.txt
RUN pip3 install -t /var/task -r /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/vector_ingestion_requirements.txt
RUN pip3 install --upgrade -t /var/task -r /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/loaders/docx_loader_requirements.txt
RUN pip3 install -t /var/task -r /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/loaders/pdf_image_loader_requirements.txt
COPY ingestion_provider/* /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/
COPY vector_store_provider/vector_store_document.py /var/task/multi_tenant_full_stack_rag_application/vector_store_provider/
COPY ingestion_provider/loaders/* /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/loaders/
COPY ingestion_provider/splitters/* /var/task/multi_tenant_full_stack_rag_application/ingestion_provider/splitters/
COPY utils/* /var/task/multi_tenant_full_stack_rag_application/utils/
CMD [ "multi_tenant_full_stack_rag_application.ingestion_provider.vector_ingestion_provider.handler" ]
