Parameters:
  Region: 
    Type: String
  CodeBuildProjectName:
    Type: String
  S3Bucket:
    Type: String
  S3Path: 
    Type: String

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement": 
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Description: Used for the codebuild jobs to build docker images and push them to ECR.
      Policies: 
        - PolicyDocument:
            Statement:
              - Action: 
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:PutImage'
                  - 'ecr:UploadLayerPart'
                Resource: '*'
                Effect: Allow
          PolicyName: codebuild-ecr-perms

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts: 
        Type: NO_ARTIFACTS
      Description: String
      EncryptionKey: String
      Environment: 
        Type: LINUX_CONTAINER
        Image: "aws/codebuild/standard:5.0"
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref Region
      Name: !Ref CodeBuildProjectName
      ResourceAccessRole: !Ref CodeBuildRole
      ServiceRole: !Ref CodeBuildRole
      Source: 
        Type: S3
        Location: 
          !Join
            - ""
            -
              - "s3://"
              - !Ref S3Bucket
              - / 
              - !Ref S3Path
      TimeoutInMinutes: 60
      Visibility: PRIVATE
