AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack that creates two nested stacks for frontend and backend
Parameters:
  AllowedEmailDomains:
    Default: amazon.com
    Description: Set the allowed email domains that are allowed to create accounts.
    Type: String
  AppName:
    Default: Multi-tenant, full-stack RAG application demo
    Description: Set the app name
    Type: String
  RemovalPolicy:
    Default: DESTROY
    Description: Set removal policy for stacks
    Type: String
  SignUpVerificationEmailBody:
    Default: Your verification code is {####}
    Description: Set the email body for sign up verification
    Type: String
  SignUpVerificationEmailSubject:
    Default: Verification code for multi-tenant, full-stack RAG application demo
    Description: Set the email subject for sign up verification
    Type: String
Resources:
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/auth-stack-template.yaml
