AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for
Parameters:
  AllowedEmailDomains:
    Description: Set the allowed email domains that are allowed to create accounts.
    Type: String
  AppName:
    Default: Multi-tenant, full-stack RAG application demo
    Description: Set the app name
    Type: String
  RemovalPolicy:
    Default: DESTROY
    Description: Set removal policy for stacks
    Type: String
  SignUpVerificationEmailBody:
    Default: Your verification code is {####}
    Description: Set the email body for sign up verification
    Type: String
  SignUpVerificationEmailSubject:
    Default: Verification code for multi-tenant, full-stack RAG application demo
    Description: Set the email subject for sign up verification
    Type: String
Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/vpc-stack-template.yaml
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        allowedEmailDomains: Ref: AllowedEmailDomains
        appName: Ref: AppName
        removalPolicy: Ref: RemovalPolicy
        signUpVerificationEmailBody: Ref: SignUpVerificationEmailBody
        signUpVerificationEmailSubject: Ref: SignUpVerificationEmailSubject
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/auth-stack-template.yaml
  BedrockStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/bedrock-stack-template.yaml
  DocCollectionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/doc-collections-stack-template.yaml
  EmbeddingsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/embeddings-stack-template.yaml
  EnrichmentPipelinesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/enrichment-pipelines-stack-template.yaml
  GenerationHandlerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/generation-handler-stack-template.yaml
  GraphStoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/graph-store-stack-template.yaml
  IngestionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/ingestion-stack-template.yaml
  PromptTemplatesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/prompt-templates-stack-template.yaml
  UIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/ui-stack-template.yaml
  VectorStoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/vector-store-stack-template.yaml
  FinalStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   EnvironmentName: dev
      TemplateURL: https://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}.s3.{region}.amazonaws.com/{output_prefix}/mtfsrad-final-stack-template.yaml
