Resources:
  BedrockProviderFunctionServiceRoleEA34841A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/BedrockProviderStack/BedrockProviderFunction/ServiceRole/Resource
  BedrockProviderFunctionServiceRoleDefaultPolicyA2EB8301:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: bedrock:*
            Effect: Allow
            Resource: "*"
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::ImportValue: mtfsradbdevAuthProviderStackCCE112F5:ExportsOutputFnGetAttCognitoStackNestedStackCognitoStackNestedStackResource95DF2EBAOutputsmtfsradbdevAuthProviderStackCognitoStackCognitoAuthProviderFunction314FA51DArnCBC57E5D
          - Action:
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/mtfsrad-b-dev*
        Version: "2012-10-17"
      PolicyName: BedrockProviderFunctionServiceRoleDefaultPolicyA2EB8301
      Roles:
        - Ref: BedrockProviderFunctionServiceRoleEA34841A
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/BedrockProviderStack/BedrockProviderFunction/ServiceRole/DefaultPolicy/Resource
  BedrockProviderFunctionSecurityGroup72A5B4FB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Automatic security group for Lambda Function mtfsradbdevBedrockProviderStackBedrockProviderFunction3097D1D9
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId:
        Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpc8378EB38272D6E3A
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/BedrockProviderStack/BedrockProviderFunction/SecurityGroup/Resource
  BedrockProviderFunction99614D39:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 3fcf5e016a1a04f68ca49ea2726795fcf25c784f8fda0949532003b5539a95f8.zip
      Environment:
        Variables:
          STACK_NAME: mtfsrad-b-dev
      Handler: multi_tenant_full_stack_rag_application.bedrock_provider.bedrock_provider.handler
      MemorySize: 256
      Role:
        Fn::GetAtt:
          - BedrockProviderFunctionServiceRoleEA34841A
          - Arn
      Runtime: python3.11
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt:
              - BedrockProviderFunctionSecurityGroup72A5B4FB
              - GroupId
        SubnetIds:
          - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpcdataisolatedSubnet1SubnetEBF5BB657298517B
          - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpcdataisolatedSubnet2Subnet8AADF05A8CCED4C9
    DependsOn:
      - BedrockProviderFunctionServiceRoleDefaultPolicyA2EB8301
      - BedrockProviderFunctionServiceRoleEA34841A
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/BedrockProviderStack/BedrockProviderFunction/Resource
      aws:asset:path: asset.3fcf5e016a1a04f68ca49ea2726795fcf25c784f8fda0949532003b5539a95f8
      aws:asset:is-bundled: true
      aws:asset:property: Code
  BedrockProviderFunctionNameC688AF4B:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/bedrock_provider_function_name
      Type: String
      Value:
        Ref: BedrockProviderFunction99614D39
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/BedrockProviderStack/BedrockProviderFunctionName/Resource
  CognitoAuthRoleRefPolicymtfsradbdevBedrockProviderStackCognitoAuthRoleRefA521E1127A59E211:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - BedrockProviderFunction99614D39
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - BedrockProviderFunction99614D39
                        - Arn
                    - :*
        Version: "2012-10-17"
      PolicyName: PolicymtfsradbdevBedrockProviderStackCognitoAuthRoleRefA521E112
      Roles:
        - Fn::Select:
            - 1
            - Fn::Split:
                - /
                - Fn::Select:
                    - 5
                    - Fn::Split:
                        - ":"
                        - Fn::ImportValue: mtfsradbdevAuthProviderStackCCE112F5:ExportsOutputFnGetAttCognitoStackNestedStackCognitoStackNestedStackResource95DF2EBAOutputsmtfsradbdevAuthProviderStackCognitoStackCognitoIdentityPoolAuthenticatedRole7703D556Arn606C0A72
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/BedrockProviderStack/CognitoAuthRoleRef/PolicymtfsradbdevBedrockProviderStackCognitoAuthRoleRefA521E112/Resource
