Outputs:
  EmbeddingsProviderFunctionArnOutput:
    Export:
      Name: EmbeddingsProviderFunctionArn
    Value:
      Fn::GetAtt:
        - EmbeddingsProviderFunction749E762A
        - Arn

Resources:
  EmbeddingsProviderFunctionServiceRoleBF095A5C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EmbeddingsProviderStack/EmbeddingsProviderFunction/ServiceRole/Resource
  EmbeddingsProviderFunctionServiceRoleDefaultPolicyDC3F6F28:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: bedrock:InvokeModel
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:bedrock:"
                  - Ref: AWS::Region
                  - ::foundation-model/*
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - !ImportValue AuthProviderFunctionArn
              - !ImportValue BedrockProviderFunctionArn
              - Fn::Join:
                  - ""
                  - - BedrockProviderFunctionArn
                    - :*
          - Action:
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/mtfsrad-b-dev*
        Version: "2012-10-17"
      PolicyName: EmbeddingsProviderFunctionServiceRoleDefaultPolicyDC3F6F28
      Roles:
        - Ref: EmbeddingsProviderFunctionServiceRoleBF095A5C
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EmbeddingsProviderStack/EmbeddingsProviderFunction/ServiceRole/DefaultPolicy/Resource
  EmbeddingsProviderFunction749E762A:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: c74147e2a38b5b318115605803f70a0b2d8a5ae157ca16a8ea191c1b4116dd4b.zip
      Environment:
        Variables:
          EMBEDDINGS_MODEL_ID: amazon.titan-embed-text-v2:0
          EMBEDDINGS_PROVIDER_ARGS: '["amazon.titan-embed-text-v2:0"]'
          EMBEDDINGS_PROVIDER_PY_PATH: multi_tenant_full_stack_rag_application_demo.embeddings_provider.bedrock_embeddings_provider.BedrockEmbeddingsProvider
          STACK_NAME: mtfsrad-b-dev
      Handler: multi_tenant_full_stack_rag_application.embeddings_provider.bedrock_embeddings_provider.handler
      MemorySize: 256
      Role:
        Fn::GetAtt:
          - EmbeddingsProviderFunctionServiceRoleBF095A5C
          - Arn
      Runtime: python3.11
      Timeout: 60
    DependsOn:
      - EmbeddingsProviderFunctionServiceRoleDefaultPolicyDC3F6F28
      - EmbeddingsProviderFunctionServiceRoleBF095A5C
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EmbeddingsProviderStack/EmbeddingsProviderFunction/Resource
      aws:asset:path: asset.c74147e2a38b5b318115605803f70a0b2d8a5ae157ca16a8ea191c1b4116dd4b
      aws:asset:is-bundled: true
      aws:asset:property: Code
  EmbeddingsProviderFunctionName2F1A37B2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/embeddings_provider_function_name
      Type: String
      Value:
        Ref: EmbeddingsProviderFunction749E762A
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EmbeddingsProviderStack/EmbeddingsProviderFunctionName/Resource
  EmbeddingsProviderOriginF71CED89:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/origin_embeddings_provider
      Type: String
      Value:
        Ref: EmbeddingsProviderFunction749E762A
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EmbeddingsProviderStack/EmbeddingsProviderOrigin/Resource
  CognitoAuthRoleRefPolicymtfsradbdevEmbeddingsProviderStackCognitoAuthRoleRefEF8CD79840B9523E:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - EmbeddingsProviderFunction749E762A
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - EmbeddingsProviderFunction749E762A
                        - Arn
                    - :*
        Version: "2012-10-17"
      PolicyName: PolicymtfsradbdevEmbeddingsProviderStackCognitoAuthRoleRefEF8CD798
      Roles:
        - Fn::Select:
            - 1
            - Fn::Split:
                - /
                - Fn::Select:
                    - 5
                    - Fn::Split:
                        - ":"
                        - !ImportValue CognitoAuthenticatedRoleArn
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EmbeddingsProviderStack/CognitoAuthRoleRef/PolicymtfsradbdevEmbeddingsProviderStackCognitoAuthRoleRefEF8CD798/Resource
