Resources:
  EnabledEnrichmentPipelinesParamCD4062A4:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/enabled_enrichment_pipelines
      Type: String
      Value: '{"entity_extraction": {"name": "Entity Extraction"}}'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EnrichmentPipelinesHandlerStack/EnabledEnrichmentPipelinesParam/Resource
  EntityExtractionProviderFunctionEntityExtractionFunctionServiceRole10D061E8:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EnrichmentPipelinesHandlerStack/EntityExtractionProviderFunction/EntityExtractionFunction/ServiceRole/Resource
  EntityExtractionProviderFunctionEntityExtractionFunctionServiceRoleDefaultPolicy289CB5F4:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/mtfsrad-b-dev*
          - Action: dynamodb:ListStreams
            Effect: Allow
            Resource: "*"
          - Action:
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
            Effect: Allow
            Resource:
              Fn::ImportValue: mtfsradbdevIngestionProviderStack7EBE4178:ExportsOutputFnGetAttDdbTableIngestionStatusTable32816510StreamArn439B6DA3
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::ImportValue: mtfsradbdevIngestionProviderStack7EBE4178:ExportsOutputFnGetAttDdbTableIngestionStatusTable32816510Arn05D791B1
              - Ref: AWS::NoValue
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - Fn::ImportValue: mtfsradbdevBedrockProviderStack1AABA887:ExportsOutputFnGetAttBedrockProviderFunction99614D39ArnA074F27C
              - Fn::ImportValue: mtfsradbdevDocumentCollectionsHandlerStack7FE01056:ExportsOutputFnGetAttDocCollectionsHandlerFunctionB290B79CArn454F6B72
              - Fn::ImportValue: mtfsradbdevGraphStoreProviderStack87AD9906:ExportsOutputFnGetAttGraphStoreProviderFunctionE449DC25ArnEA333257
              - Fn::ImportValue: mtfsradbdevIngestionProviderStack7EBE4178:ExportsOutputFnGetAttIngestionStatusProviderFunctionE9E064BFArn2D6E7177
              - Fn::ImportValue: mtfsradbdevPromptTemplateHandlerStack05579D4E:ExportsOutputFnGetAttPromptTemplateHandlerFunction2A6BF5FFArnCCEB5505
              - Fn::ImportValue: mtfsradbdevVectorStoreProviderStackD15A38D1:portsOutputFnGetAttOpenSearchManagedStackNestedStackOpenSearchManagedStackNestedStackResource253201F9OutputsmtfsradbdevVectorStoreProviderStackOpenSearchManagedStackVectorStoreProviderFunction71969801Arn911E4BA2
              - Fn::Join:
                  - ""
                  - - Fn::ImportValue: mtfsradbdevBedrockProviderStack1AABA887:ExportsOutputFnGetAttBedrockProviderFunction99614D39ArnA074F27C
                    - :*
              - Fn::Join:
                  - ""
                  - - Fn::ImportValue: mtfsradbdevDocumentCollectionsHandlerStack7FE01056:ExportsOutputFnGetAttDocCollectionsHandlerFunctionB290B79CArn454F6B72
                    - :*
              - Fn::Join:
                  - ""
                  - - Fn::ImportValue: mtfsradbdevGraphStoreProviderStack87AD9906:ExportsOutputFnGetAttGraphStoreProviderFunctionE449DC25ArnEA333257
                    - :*
              - Fn::Join:
                  - ""
                  - - Fn::ImportValue: mtfsradbdevIngestionProviderStack7EBE4178:ExportsOutputFnGetAttIngestionStatusProviderFunctionE9E064BFArn2D6E7177
                    - :*
              - Fn::Join:
                  - ""
                  - - Fn::ImportValue: mtfsradbdevPromptTemplateHandlerStack05579D4E:ExportsOutputFnGetAttPromptTemplateHandlerFunction2A6BF5FFArnCCEB5505
                    - :*
              - Fn::Join:
                  - ""
                  - - Fn::ImportValue: mtfsradbdevVectorStoreProviderStackD15A38D1:portsOutputFnGetAttOpenSearchManagedStackNestedStackOpenSearchManagedStackNestedStackResource253201F9OutputsmtfsradbdevVectorStoreProviderStackOpenSearchManagedStackVectorStoreProviderFunction71969801Arn911E4BA2
                    - :*
        Version: "2012-10-17"
      PolicyName: EntityExtractionProviderFunctionEntityExtractionFunctionServiceRoleDefaultPolicy289CB5F4
      Roles:
        - Ref: EntityExtractionProviderFunctionEntityExtractionFunctionServiceRole10D061E8
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EnrichmentPipelinesHandlerStack/EntityExtractionProviderFunction/EntityExtractionFunction/ServiceRole/DefaultPolicy/Resource
  EntityExtractionProviderFunctionEntityExtractionFunctionF7D05F2D:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 46cb8e36b1669dfc3536b7b70dceb95eb31f640a56dde27430b4f3c8cdd5e817.zip
      Environment:
        Variables:
          AWS_ACCOUNT_ID:
            Ref: AWS::AccountId
          EXTRACTION_MODEL_ID: anthropic.claude-3-haiku-20240307-v1:0
          SERVICE_REGION:
            Ref: AWS::Region
          STACK_NAME: mtfsrad-b-dev
      Handler: multi_tenant_full_stack_rag_application.enrichment_pipelines_provider.entity_extraction.handler
      MemorySize: 1024
      Role:
        Fn::GetAtt:
          - EntityExtractionProviderFunctionEntityExtractionFunctionServiceRole10D061E8
          - Arn
      Runtime: python3.11
      Timeout: 900
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputFnGetAttAppSecurityGroupC396D536GroupId4ECD26A6
        SubnetIds:
          - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpcdataisolatedSubnet1SubnetEBF5BB657298517B
          - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpcdataisolatedSubnet2Subnet8AADF05A8CCED4C9
    DependsOn:
      - EntityExtractionProviderFunctionEntityExtractionFunctionServiceRoleDefaultPolicy289CB5F4
      - EntityExtractionProviderFunctionEntityExtractionFunctionServiceRole10D061E8
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EnrichmentPipelinesHandlerStack/EntityExtractionProviderFunction/EntityExtractionFunction/Resource
      aws:asset:path: asset.46cb8e36b1669dfc3536b7b70dceb95eb31f640a56dde27430b4f3c8cdd5e817
      aws:asset:is-bundled: true
      aws:asset:property: Code
  EntityExtractionProviderFunctionEntityExtractionFunctionDynamoDBEventSourcemtfsradbdevIngestionProviderStackDdbTableIngestionStatusTableEEDEF768415DECF9:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn:
        Fn::ImportValue: mtfsradbdevIngestionProviderStack7EBE4178:ExportsOutputFnGetAttDdbTableIngestionStatusTable32816510StreamArn439B6DA3
      FilterCriteria:
        Filters:
          - Pattern: '{"eventName":["MODIFY"]}'
      FunctionName:
        Ref: EntityExtractionProviderFunctionEntityExtractionFunctionF7D05F2D
      MaximumRetryAttempts: 2
      StartingPosition: LATEST
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EnrichmentPipelinesHandlerStack/EntityExtractionProviderFunction/EntityExtractionFunction/DynamoDBEventSource:mtfsradbdevIngestionProviderStackDdbTableIngestionStatusTableEEDEF768/Resource
  EntityExtractionProviderFunctionEntityExtractionProviderOriginB2CBC92A:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/origin_entity_extraction
      Type: String
      Value:
        Ref: EntityExtractionProviderFunctionEntityExtractionFunctionF7D05F2D
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/EnrichmentPipelinesHandlerStack/EntityExtractionProviderFunction/EntityExtractionProviderOrigin/Resource
