Outputs:
  GraphStoreProviderFunctionArnOutput:
    Export:
      Name: GraphStoreProviderFunctionArn
    Value: 
      Fn::GetAtt:
        - GenerationHandlerFunction7E4CE896
        - Arn
Resources:
  GhCognitoAuthRoleRefPolicymtfsradbdevGenerationHandlerApiStackGhCognitoAuthRoleRef55C2622EEF908316:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - GenerationHandlerFunction7E4CE896
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - GenerationHandlerFunction7E4CE896
                        - Arn
                    - :*
        Version: "2012-10-17"
      PolicyName: PolicymtfsradbdevGenerationHandlerApiStackGhCognitoAuthRoleRef55C2622E
      Roles:
        - Fn::Select:
            - 1
            - Fn::Split:
                - /
                - Fn::Select:
                    - 5
                    - Fn::Split:
                        - ":"
                        - !ImportValue CognitoAuthenticatedRoleArn
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GhCognitoAuthRoleRef/PolicymtfsradbdevGenerationHandlerApiStackGhCognitoAuthRoleRef55C2622E/Resource
  GenerationHandlerFunctionServiceRole191FABCF:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerFunction/ServiceRole/Resource
  GenerationHandlerFunctionServiceRoleDefaultPolicyD6730C32:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/mtfsrad-b-dev*
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - !ImportValue AuthProviderFunctionArn
              - !ImportValue BedrockProviderFunctionArn
              - !ImportValue DocCollectionsHandlerFunctionArn
              - !ImportValue EmbeddingsProviderFunctionArn
              - !ImportValue IngestionStatusProviderFunctionArn
              - !ImportValue PromptTemplatesHandlerFunctionArn
              - !ImportValue VectorStoreProviderFunctionArn
              - Fn::Join:
                  - ""
                  - - !ImportValue BedrockProviderFunctionArn
                    - :*
              - Fn::Join:
                  - ""
                  - - !ImportValue DocCollectionsHandlerFunctionArn
                    - :*
              - Fn::Join:
                  - ""
                  - - !ImportValue EmbeddingsProviderFunctionArn
                    - :*
              - Fn::Join:
                  - ""
                  - - !ImportValue IngestionStatusProviderFunctionArn
                    - :*
              - Fn::Join:
                  - ""
                  - - !ImportValue PromptTemplatesHandlerFunctionArn
                    - :*
              - Fn::Join:
                  - ""
                  - - !ImportValue VectorStoreProviderFunctionArn
                    - :*
          - Action:
              - es:ESHttpGet
              - es:ESHttpHead
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - !ImportValue OpenSearchDomainArn
                    - /*
              - Fn::Join:
                  - ""
                  - - !ImportValue OpenSearchDomainArn
                    - /*/*
        Version: "2012-10-17"
      PolicyName: GenerationHandlerFunctionServiceRoleDefaultPolicyD6730C32
      Roles:
        - Ref: GenerationHandlerFunctionServiceRole191FABCF
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerFunction/ServiceRole/DefaultPolicy/Resource
  GenerationHandlerFunction7E4CE896:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 601aa5b627c6cd66021ebea21d8bcadafa976351a444cfde7e78af235b62863c.zip
      Environment:
        Variables:
          STACK_NAME: mtfsrad-b-dev
      Handler: multi_tenant_full_stack_rag_application.generation_handler.generation_handler.handler
      MemorySize: 768
      Role:
        Fn::GetAtt:
          - GenerationHandlerFunctionServiceRole191FABCF
          - Arn
      Runtime: python3.11
      Timeout: 120
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue AppSecurityGroupId
        SubnetIds:
          - !ImportValue PrivateIsolatedSubnetId1
          - !ImportValue PrivateIsolatedSubnetId2
    DependsOn:
      - GenerationHandlerFunctionServiceRoleDefaultPolicyD6730C32
      - GenerationHandlerFunctionServiceRole191FABCF
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerFunction/Resource
      aws:asset:path: asset.601aa5b627c6cd66021ebea21d8bcadafa976351a444cfde7e78af235b62863c
      aws:asset:is-bundled: true
      aws:asset:property: Code
  GenerationHandlerApi69F9E661:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: generation
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/Resource
  GenerationHandlerApiDefaultStage5B1553FC:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: GenerationHandlerApi69F9E661
      AutoDeploy: true
      StageName: $default
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/DefaultStage/Resource
  GenerationHandlerApiGETgenerationGenerationHandlerLambdaIntegration328895FF:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: GenerationHandlerApi69F9E661
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - GenerationHandlerFunction7E4CE896
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/GET--generation/GenerationHandlerLambdaIntegration/Resource
  GenerationHandlerApiGETgenerationGenerationHandlerLambdaIntegrationPermission10C5AED1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GenerationHandlerFunction7E4CE896
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: GenerationHandlerApi69F9E661
            - /*/*/generation
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/GET--generation/GenerationHandlerLambdaIntegration-Permission
  GenerationHandlerApiGETgenerationC8404037:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: GenerationHandlerApi69F9E661
      AuthorizationType: JWT
      AuthorizerId:
        Ref: GenerationHandlerApiGenerationHandlerAuthorizerD333EE82
      RouteKey: GET /generation
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: GenerationHandlerApiGETgenerationGenerationHandlerLambdaIntegration328895FF
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/GET--generation/Resource
  GenerationHandlerApiGenerationHandlerAuthorizerD333EE82:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId:
        Ref: GenerationHandlerApi69F9E661
      AuthorizerType: JWT
      IdentitySource:
        - $request.header.Authorization
      JwtConfiguration:
        Audience:
          - !ImportValue CognitoUserPoolClientId
        Issuer:
          Fn::Join:
            - ""
            - - https://cognito-idp.
              - Ref: AWS::Region
              - .amazonaws.com/
              - !ImportValue CognitoUserPoolId
      Name: GenerationHandlerAuthorizer
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/GenerationHandlerAuthorizer/Resource
  GenerationHandlerApiPOSTgenerationGenerationHandlerLambdaIntegrationPermission09EBE7A8:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GenerationHandlerFunction7E4CE896
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: GenerationHandlerApi69F9E661
            - /*/*/generation
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/POST--generation/GenerationHandlerLambdaIntegration-Permission
  GenerationHandlerApiPOSTgeneration2BD8378B:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: GenerationHandlerApi69F9E661
      AuthorizationType: JWT
      AuthorizerId:
        Ref: GenerationHandlerApiGenerationHandlerAuthorizerD333EE82
      RouteKey: POST /generation
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: GenerationHandlerApiGETgenerationGenerationHandlerLambdaIntegration328895FF
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/POST--generation/Resource
  GenerationHandlerApiOPTIONSproxyGenerationHandlerLambdaIntegrationPermissionECA8EFB2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GenerationHandlerFunction7E4CE896
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: GenerationHandlerApi69F9E661
            - /*/*/{proxy+}
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/OPTIONS--{proxy+}/GenerationHandlerLambdaIntegration-Permission
  GenerationHandlerApiOPTIONSproxy46348D0B:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: GenerationHandlerApi69F9E661
      AuthorizationType: NONE
      RouteKey: OPTIONS /{proxy+}
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: GenerationHandlerApiGETgenerationGenerationHandlerLambdaIntegration328895FF
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerApi/OPTIONS--{proxy+}/Resource
  GenerationHandlerHttpApiUrlParam545B9410:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/generation_handler_api_url
      Type: String
      Value:
        Fn::Join:
          - ""
          - - https://
            - Ref: GenerationHandlerApi69F9E661
            - .execute-api.
            - Ref: AWS::Region
            - "."
            - Ref: AWS::URLSuffix
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerHttpApiUrlParam/Resource
  GenerationHandlerOriginParam790DC1BE:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/origin_generation_handler
      Type: String
      Value:
        Ref: GenerationHandlerFunction7E4CE896
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GenerationHandlerApiStack/GenerationHandlerOriginParam/Resource
