Resources:
  CognitoAuthRoleRefPolicymtfsradbdevGraphStoreProviderStackCognitoAuthRoleRef61A9C55F736B8C00:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - GraphStoreProviderFunctionE449DC25
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - GraphStoreProviderFunctionE449DC25
                        - Arn
                    - :*
        Version: "2012-10-17"
      PolicyName: PolicymtfsradbdevGraphStoreProviderStackCognitoAuthRoleRef61A9C55F
      Roles:
        - Fn::Select:
            - 1
            - Fn::Split:
                - /
                - Fn::Select:
                    - 5
                    - Fn::Split:
                        - ":"
                        - Fn::ImportValue: mtfsradbdevAuthProviderStackCCE112F5:ExportsOutputFnGetAttCognitoStackNestedStackCognitoStackNestedStackResource95DF2EBAOutputsmtfsradbdevAuthProviderStackCognitoStackCognitoIdentityPoolAuthenticatedRole7703D556Arn606C0A72
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/CognitoAuthRoleRef/PolicymtfsradbdevGraphStoreProviderStackCognitoAuthRoleRef61A9C55F/Resource
  GraphStoreProviderFunctionServiceRole068FDA4A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/GraphStoreProviderFunction/ServiceRole/Resource
  GraphStoreProviderFunctionServiceRoleDefaultPolicyEEB86B6A:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/mtfsrad-b-dev*
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::ImportValue: mtfsradbdevAuthProviderStackCCE112F5:ExportsOutputFnGetAttCognitoStackNestedStackCognitoStackNestedStackResource95DF2EBAOutputsmtfsradbdevAuthProviderStackCognitoStackCognitoAuthProviderFunction314FA51DArnCBC57E5D
          - Action:
              - neptune-db:*
              - neptune-db:ReadDataViaQuery
              - neptune-db:WriteDataViaQuery
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":neptune-db:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":"
                  - Fn::GetAtt:
                      - NeptuneStackGraphDatabase6D5299C6
                      - ClusterResourceId
                  - /*
        Version: "2012-10-17"
      PolicyName: GraphStoreProviderFunctionServiceRoleDefaultPolicyEEB86B6A
      Roles:
        - Ref: GraphStoreProviderFunctionServiceRole068FDA4A
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/GraphStoreProviderFunction/ServiceRole/DefaultPolicy/Resource
  GraphStoreProviderFunctionE449DC25:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 3dea65d96c197b3de9a79997da803f80249ade0e764ae21ba0caccd9f11dace6.zip
      Environment:
        Variables:
          STACK_NAME: mtfsrad-b-dev
          SERVICE_REGION:
            Ref: AWS::Region
      Handler: multi_tenant_full_stack_rag_application.graph_store_provider.neptune_graph_store_provider.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - GraphStoreProviderFunctionServiceRole068FDA4A
          - Arn
      Runtime: python3.11
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputFnGetAttAppSecurityGroupC396D536GroupId4ECD26A6
        SubnetIds:
          - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpcdataisolatedSubnet1SubnetEBF5BB657298517B
          - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpcdataisolatedSubnet2Subnet8AADF05A8CCED4C9
    DependsOn:
      - GraphStoreProviderFunctionServiceRoleDefaultPolicyEEB86B6A
      - GraphStoreProviderFunctionServiceRole068FDA4A
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/GraphStoreProviderFunction/Resource
      aws:asset:path: asset.3dea65d96c197b3de9a79997da803f80249ade0e764ae21ba0caccd9f11dace6
      aws:asset:is-bundled: true
      aws:asset:property: Code
  GraphStoreProviderFunctionName65C71684:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/graph_store_provider_function_name
      Type: String
      Value:
        Ref: GraphStoreProviderFunctionE449DC25
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/GraphStoreProviderFunctionName/Resource
  NeptuneStackGraphDatabaseSubnetsDB3BA7F8:
    Type: AWS::Neptune::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for GraphDatabase database
      SubnetIds:
        - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpcdataisolatedSubnet1SubnetEBF5BB657298517B
        - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputRefVpcdataisolatedSubnet2Subnet8AADF05A8CCED4C9
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/NeptuneStack/GraphDatabase/Subnets/Resource
  NeptuneStackGraphDatabase6D5299C6:
    Type: AWS::Neptune::DBCluster
    Properties:
      DBSubnetGroupName:
        Ref: NeptuneStackGraphDatabaseSubnetsDB3BA7F8
      IamAuthEnabled: true
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - Fn::ImportValue: mtfsradbdevVpc39114410:ExportsOutputFnGetAttAppSecurityGroupC396D536GroupId4ECD26A6
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/NeptuneStack/GraphDatabase/Resource
  NeptuneStackGraphDatabaseInstance1A10B58B9:
    Type: AWS::Neptune::DBInstance
    Properties:
      AutoMinorVersionUpgrade: false
      DBClusterIdentifier:
        Ref: NeptuneStackGraphDatabase6D5299C6
      DBInstanceClass: db.t4g.medium
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/NeptuneStack/GraphDatabase/Instance1
  NeptuneStackNeptuneEndpointAddressParameter9A5C0F80:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/neptune_endpoint_address
      Type: String
      Value:
        Fn::Join:
          - ""
          - - Fn::GetAtt:
                - NeptuneStackGraphDatabase6D5299C6
                - Endpoint
            - ":"
            - Fn::GetAtt:
                - NeptuneStackGraphDatabase6D5299C6
                - Port
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/GraphStoreProviderStack/NeptuneStack/NeptuneEndpointAddressParameter/Resource
