Outputs:
  PromptTemplateHandlerFunctionArnOutput:
    Export:
      Name: PromptTemplateHandlerFunctionArn
    Value: 
      Fn::GetAtt:
        - PromptTemplateHandlerFunction2A6BF5FF
        - Arn
Resources:
  PTCognitoAuthRolePolicymtfsradbdevPromptTemplateHandlerStackPTCognitoAuthRole6E2F3592C9501BC7:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - PromptTemplateHandlerFunction2A6BF5FF
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - PromptTemplateHandlerFunction2A6BF5FF
                        - Arn
                    - :*
          - Action:
              - apigateway:DELETE
              - apigateway:GET
              - apigateway:POST
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:apigateway:"
                  - Ref: AWS::Region
                  - ::/apis/
                  - Ref: PromptTemplateHandlerHttpApiE4B49A12
                  - /*
        Version: "2012-10-17"
      PolicyName: PolicymtfsradbdevPromptTemplateHandlerStackPTCognitoAuthRole6E2F3592
      Roles:
        - Fn::Select:
            - 1
            - Fn::Split:
                - /
                - Fn::Select:
                    - 5
                    - Fn::Split:
                        - ":"
                        - !ImportValue CognitoAuthenticatedRoleArn
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PTCognitoAuthRole/PolicymtfsradbdevPromptTemplateHandlerStackPTCognitoAuthRole6E2F3592/Resource
  PromptTemplatesTableD62549A1:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: S
        - AttributeName: template_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: by_template_id
          KeySchema:
            - AttributeName: template_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplatesTable/PromptTemplatesTable/Resource
  PromptTemplateHandlerFunctionServiceRole21920E21:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerFunction/ServiceRole/Resource
  PromptTemplateHandlerFunctionServiceRoleDefaultPolicyA4BEE58B:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - PromptTemplatesTableD62549A1
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - PromptTemplatesTableD62549A1
                        - Arn
                    - /index/*
          - Action:
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/mtfsrad-b-dev*
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              !ImportValue AuthProviderFunctionArn
        Version: "2012-10-17"
      PolicyName: PromptTemplateHandlerFunctionServiceRoleDefaultPolicyA4BEE58B
      Roles:
        - Ref: PromptTemplateHandlerFunctionServiceRole21920E21
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerFunction/ServiceRole/DefaultPolicy/Resource
  PromptTemplateHandlerFunctionSecurityGroup8C913856:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Automatic security group for Lambda Function mtfsradbdevPromptTemplateHandlerStackPromptTemplateHandlerFunctionDA55EB20
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId:
        !ImportValue VpcId
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerFunction/SecurityGroup/Resource
  PromptTemplateHandlerFunction2A6BF5FF:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 73f1084025205bec16aa142276f3abf3198b46dc456721c8a98c1d336c9bc505.zip
      Environment:
        Variables:
          PROMPT_TEMPLATES_TABLE:
            Ref: PromptTemplatesTableD62549A1
          STACK_NAME: mtfsrad-b-dev
      Handler: multi_tenant_full_stack_rag_application.prompt_template_handler.prompt_template_handler.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - PromptTemplateHandlerFunctionServiceRole21920E21
          - Arn
      Runtime: python3.11
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt:
              - PromptTemplateHandlerFunctionSecurityGroup8C913856
              - GroupId
        SubnetIds:
          - !ImportValue PrivateIsolatedSubnetId1
          - !ImportValue PrivateIsolatedSubnetId2
    DependsOn:
      - PromptTemplateHandlerFunctionServiceRoleDefaultPolicyA4BEE58B
      - PromptTemplateHandlerFunctionServiceRole21920E21
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerFunction/Resource
      aws:asset:path: asset.73f1084025205bec16aa142276f3abf3198b46dc456721c8a98c1d336c9bc505
      aws:asset:is-bundled: true
      aws:asset:property: Code
  PromptTemplateHandlerFunctionNameParamC5C0B3F1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/prompt_template_handler_function_name
      Type: String
      Value:
        Ref: PromptTemplateHandlerFunction2A6BF5FF
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerFunctionNameParam/Resource
  PromptTemplateHandlerOriginParamFEDB1F9E:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/origin_prompt_template_handler
      Type: String
      Value:
        Ref: PromptTemplateHandlerFunction2A6BF5FF
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerOriginParam/Resource
  PromptTemplateHandlerHttpApiE4B49A12:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: prompt_templates
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/Resource
  PromptTemplateHandlerHttpApiDefaultStageAED389BF:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: PromptTemplateHandlerHttpApiE4B49A12
      AutoDeploy: true
      StageName: $default
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/DefaultStage/Resource
  PromptTemplateHandlerHttpApiGETprompttemplatesPromptTemplateHandlerLambdaIntegration4B360C50:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: PromptTemplateHandlerHttpApiE4B49A12
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - PromptTemplateHandlerFunction2A6BF5FF
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/GET--prompt_templates/PromptTemplateHandlerLambdaIntegration/Resource
  PromptTemplateHandlerHttpApiGETprompttemplatesPromptTemplateHandlerLambdaIntegrationPermissionBCC69B31:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - PromptTemplateHandlerFunction2A6BF5FF
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: PromptTemplateHandlerHttpApiE4B49A12
            - /*/*/prompt_templates
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/GET--prompt_templates/PromptTemplateHandlerLambdaIntegration-Permission
  PromptTemplateHandlerHttpApiGETprompttemplatesEFF75E52:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: PromptTemplateHandlerHttpApiE4B49A12
      AuthorizationType: JWT
      AuthorizerId:
        Ref: PromptTemplateHandlerHttpApiPromptTemplateHandlerAuthorizerB18A4C1F
      RouteKey: GET /prompt_templates
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: PromptTemplateHandlerHttpApiGETprompttemplatesPromptTemplateHandlerLambdaIntegration4B360C50
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/GET--prompt_templates/Resource
  PromptTemplateHandlerHttpApiPromptTemplateHandlerAuthorizerB18A4C1F:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId:
        Ref: PromptTemplateHandlerHttpApiE4B49A12
      AuthorizerType: JWT
      IdentitySource:
        - $request.header.Authorization
      JwtConfiguration:
        Audience:
          - !ImportValue CognitoUserPoolClientId
        Issuer:
          Fn::Join:
            - ""
            - - https://cognito-idp.
              - Ref: AWS::Region
              - .amazonaws.com/
              - !ImportValue CognitoUserPoolId
      Name: PromptTemplateHandlerAuthorizer
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/PromptTemplateHandlerAuthorizer/Resource
  PromptTemplateHandlerHttpApiPOSTprompttemplatesPromptTemplateHandlerLambdaIntegrationPermission8B2F93BD:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - PromptTemplateHandlerFunction2A6BF5FF
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: PromptTemplateHandlerHttpApiE4B49A12
            - /*/*/prompt_templates
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/POST--prompt_templates/PromptTemplateHandlerLambdaIntegration-Permission
  PromptTemplateHandlerHttpApiPOSTprompttemplatesCC4D38EB:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: PromptTemplateHandlerHttpApiE4B49A12
      AuthorizationType: JWT
      AuthorizerId:
        Ref: PromptTemplateHandlerHttpApiPromptTemplateHandlerAuthorizerB18A4C1F
      RouteKey: POST /prompt_templates
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: PromptTemplateHandlerHttpApiGETprompttemplatesPromptTemplateHandlerLambdaIntegration4B360C50
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/POST--prompt_templates/Resource
  PromptTemplateHandlerHttpApiGETprompttemplatestemplateidPromptTemplateHandlerLambdaIntegrationPermission4F3577BA:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - PromptTemplateHandlerFunction2A6BF5FF
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: PromptTemplateHandlerHttpApiE4B49A12
            - /*/*/prompt_templates/{template_id}
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/GET--prompt_templates--{template_id}/PromptTemplateHandlerLambdaIntegration-Permission
  PromptTemplateHandlerHttpApiGETprompttemplatestemplateid4815874F:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: PromptTemplateHandlerHttpApiE4B49A12
      AuthorizationType: JWT
      AuthorizerId:
        Ref: PromptTemplateHandlerHttpApiPromptTemplateHandlerAuthorizerB18A4C1F
      RouteKey: GET /prompt_templates/{template_id}
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: PromptTemplateHandlerHttpApiGETprompttemplatesPromptTemplateHandlerLambdaIntegration4B360C50
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/GET--prompt_templates--{template_id}/Resource
  PromptTemplateHandlerHttpApiOPTIONSproxyPromptTemplateHandlerLambdaIntegrationPermission584C5FDA:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - PromptTemplateHandlerFunction2A6BF5FF
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: PromptTemplateHandlerHttpApiE4B49A12
            - /*/*/{proxy+}
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/OPTIONS--{proxy+}/PromptTemplateHandlerLambdaIntegration-Permission
  PromptTemplateHandlerHttpApiOPTIONSproxy5F2F6EEB:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: PromptTemplateHandlerHttpApiE4B49A12
      AuthorizationType: NONE
      RouteKey: OPTIONS /{proxy+}
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: PromptTemplateHandlerHttpApiGETprompttemplatesPromptTemplateHandlerLambdaIntegration4B360C50
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerHttpApi/OPTIONS--{proxy+}/Resource
  PromptTemplateHandlerApiUrlParamE516F4C5:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /mtfsrad-b-dev/prompt_template_handler_api_url
      Type: String
      Value:
        Fn::Join:
          - ""
          - - https://
            - Ref: PromptTemplateHandlerHttpApiE4B49A12
            - .execute-api.
            - Ref: AWS::Region
            - "."
            - Ref: AWS::URLSuffix
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: mtfsrad-b-dev/PromptTemplateHandlerStack/PromptTemplateHandlerApiUrlParam/Resource
